### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by zatinu322** [zatinu322/Var-Mod-Trash-Machina#2]
- [x] if settings.yaml is missing
- [ ] -dev arg
- [x] Отслеживание файлов gdp в папке с игрой
- [x] Дополнительные условия isl для чека двигла
- [x] flet and icecream does not installing in `pip install -r requirements.txt`
- [x] checkboxes config not saving during one session
- [x] manifest content validation
- [x] if Vanilla or it's content is not avaliable
- [x] if working_set == None
